_BASE_: "Base-CIS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
    DEPTH: 50
#  OUTPUT_DIR: "MSPNet_update_v1_p2t_tiny_RT_e6_d3_v2_trans_e_d_updated/out_r50"

