_BASE_: "Base-CIS.yaml"
MODEL:
  META_ARCHITECTURE: "GLNet"
  WEIGHTS: "/home/jiao/user_data/users/lichen/GLNet/Pretrain_models/pvt_tiny.pth"  # download weights from https://github.com/whai362/PVT
  BACKBONE:
    NAME: "pvt_tiny"
  PVTV2:
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
  MSPNet:
    INSTANCE_IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
    MASK_IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
    FEAT_INSTANCE_STRIDES: [ 8, 8, 16, 32 ]
    ENC_LAYERS: 1
    DEC_LAYERS: 3
    FEAT_SCALE_RANGES: ((1, 96), (48, 192), (96, 384), (192, 2048)) #((1, 192), (48, 384), (96, 768), (192, 2048))
    NUM_GRIDS: [ 40, 36, 24, 16 ]
    SEM_LOSS: True
INPUT:
#  MIN_SIZE_TRAIN: (550, )
#  MIN_SIZE_TEST: 550
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
OUTPUT_DIR: "../GLNet_pvt_v1_T_head_e1_d3"