_BASE_: "Base-CIS.yaml"
MODEL:
  META_ARCHITECTURE: "GLNet"
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/home/jiao/users/lichen/GLNet/Pretrain_models/p2t_small.pth"  # download weights from https://github.com/
  BACKBONE:
    NAME: "p2t_small"
  RESNETS:
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
    DEPTH: 50
  GLNet:
    INSTANCE_IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
    MASK_IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
    FEAT_INSTANCE_STRIDES: [ 8, 8, 16, 32]
    ENC_LAYERS: 1
    DEC_LAYERS: 3
    FEAT_SCALE_RANGES: ((1, 96), (48, 192), (96, 384), (192, 2048)) #((1, 192), (48, 384), (96, 768), (192, 2048))
    NUM_GRIDS: [40, 36, 24, 16]
    SEM_LOSS: True
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
OUTPUT_DIR: "../GLNet_test"